### ISSUE TITLE
Please add Typings!

### ISSUE THREAD

**Issue by selenehyun** [sarukuku/object-joiner#4]
Hi I am trying to use your code

And I've added Typings to make it easier to use in a TypeScript environment:
https://github.com/selenehyun/object-joiner/commit/8f6d8abe2e0abeea32c87c58c4ed9deae620769f

Can you add this to your module and distribute it?

**Comment by selenehyun** [comment]
Don't worry now!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38494

**Comment by sarukuku** [comment]
@selenehyun thanks for bringing this up! I see you contributed to DefinitelyTyped. If you still think we should have it built in to object-joiner as well reopen this issue.
